version: "3.9"   

services:
  database:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django

  backend:
    build:
      context: .
      dockerfile: Dockerfile-b
    command: sh -c "python3 parse_docx.py && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    # volumes:
    #   - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile-f
    ports:
      - "3000:5000"
    depends_on:
      - database

