version: "3.9"   

services:
  database:
    image: postgres
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database

