variables:
- name: image-tag
  value: $(Build.BuildId)
- name: stage-name
  value: $(Build.SourceBranchName)
- name: repo-name
  value: $(Build.Repository.Name)

trigger:
- dev
- main

pool:
  name: Pool

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud-back'
    organization: 'maximche'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'MaximChe_back'
    cliProjectName: 'back'
    cliSources: '.'

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'DiplomaCR'

- task: Docker@2
  displayName: Build
  inputs:
    containerRegistry: 'DiplomaCR'
    repository: '$(Build.Repository.Name)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'    
    tags: $(image-tag)

- task: Docker@2
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: 'DiplomaCR'

- task: SonarCloudAnalyze@1

- task: replacetokens@3
  displayName: Replace tokens
  inputs:    
    targetFiles: '**/*.yaml'
    tokenPrefix: __
    tokenSuffix: __    

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'Diplomak8s'
    namespace: '$(Build.SourceBranchName)'
    manifests: '*.yaml'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'