---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:      
      imagePullSecrets:
      - name: regcred
      containers:      
      - image: maxchecr.azurecr.io/__repo-name__:__image-tag__
        name: flask
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_URL
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi          
      initContainers:
        - name: init-db
          image: maxchecr.azurecr.io/__repo-name__:__image-tag__
          command: ['sh']
          args: ['-c', "rm -Rf /app/migrations/lost+found; flask db init; flask db migrate; flask db upgrade"]
          env:
          - name: POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_URL
          volumeMounts:
          - name: flask-pvc
            mountPath: /app/migrations
      volumes:
      - name: flask-pvc
        persistentVolumeClaim:
          claimName: flask-pvc               
