---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: react
    spec:      
      imagePullSecrets:
      - name: regcred
      containers:
      - image: maxchecr.azurecr.io/__repo-name__:__image-tag__
        name: react
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP        
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 500Mi

