- hosts: all
  tasks:
  - name: install epel repo
    yum:
      name: epel-release
      state: latest
  - name: install httpd
    yum: 
      name: httpd 
      state: latest
  - name: copy index.html
    copy: 
      src: index.html 
      dest: /var/www/html/index.html    
    notify:
      - Start httpd
  - name: configure firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
    notify:
      - Start httpd
  handlers:
  - name: Start httpd
    service: 
      name: httpd 
      state: started 
      enabled: yes