- hosts: all
  tasks:  
  - name: remove httpd
    yum: 
      name: httpd 
      state: absent
  - name: remove index.html
    file:
      path: /var/www/html/index.html
      state: absent
  - name: configure firewall
    firewalld:
      service: http
      permanent: true
      state: disabled