---
- name: test register
  hosts: all
  tasks:
    - shell: cat /etc/passwd
      register: passwd_contents
    - debug: 
        msg: echo "passwd contains user ansible"
      when: passwd_contents.stdout.find('ansible') != -1
