---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: dGVzdHVzZXI= # testuser
  POSTGRES_PASSWORD: dGVzdHBhc3N3b3Jk # testpassword
  POSTGRES_DB: dGVzdGRhdGFiYXNl #testdatabase
  POSTGRES_URL: cG9zdGdyZXNxbDovL3Rlc3R1c2VyOnRlc3RwYXNzd29yZEBwb3N0Z3Jlczo1NDMyL3Rlc3RkYXRhYmFzZQ==  # postgresql://testuser:testpassword@postgres:5432/testdatabase
  