---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: dXNlcg== # user
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # password
  POSTGRES_DB: ZGF0YWJhc2U= #database
  POSTGRES_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9kYXRhYmFzZQ==  # postgresql://user:password@postgres:5432/database 