---
- name: create users using a loop
  hosts: all
  tasks: 
  - name: create users 
    user: 
      name: "{{ item.name }}"
      state: present
      groups: "{{ item.groups }}"
    loop:
      - name: alex
        groups: wheel
      - name: vova
        groups: users
      - name: max
        groups: users

