---
- name: show how debug works
  hosts: all
  vars:
    user: alex
  tasks:
  - name: show value of a fact
    debug: 
      msg: this system has {{ ansible_facts.memfree_mb }} available ram
  - name: show a custom variable
    debug: 
      var: user
      verbosity: 1 # set verbosity level 3 or higher