---
- name: configure web service
  hosts: lamp
  tasks:
    - name: this installs {{ web_package }} package
      debug:
        msg: "Installing {{ web_package }}"
    - name: this starts {{ web_service }} service
      debug:
        msg: "Starting {{ web_service }}"
...